### ISSUE TITLE
Provide a solution for policy selection during auto-negotiation from the dDTR asset

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/digital-product-pass#272]
### Description
When the dDTR is retrived we need to indicate which policies we can "auto sign".

For assets we enable the selection but for the DTRs we need to indicate which policies we are allowed to sign. Not create a policy storage but add in the configuration.

Implement policy check for assets "Membership Active" and "FrameworkSustainability and Propose dpp

1- dDTR (Autosign) -> Check the policy if has the contraints from the configuration

2- DPP Asset (Manual or Autosign) -> User selects or checks contraints from configuration

Follow description from the data souvereignity guidelines

In the configuration we indicate the contraints to be validated and choosen when selecting a contract and a policy from the contract catalog.

For continue with the autosign is necesary to fullfill the constraints from the configuration. In case there is more than one policy fullfilling this constraints, take the one that appears first.

The contraint configuration is flexible for different types

### Acceptance Criteria

- [ ]  Be able to configure policies for the digital twin registry
- [ ] Be able to configure policies for the asset auto negotiation when enabled

### Additional Information

4 Story points of work have already been done and burned in JIRA

**Comment by matbmoser** [comment]
Configurations for policies are defined in this structure in (dtr and passport) configurations:
```yaml
    policyCheck:
      enable: true
      # List of allowed permissions policies
      permission:
        - action: "use"
          logicConstraint: "odrl:and"
          constraints:
          - leftOperand: "cx-policy:UsagePurpose"
            operator: "eq"
            rightOperand: "cx.core.digitalTwinRegistry:1"
          - leftOperand: "Membership"
            operator: "eq"
            rightOperand: "active"
        - action: "use"
          logicConstraint: "odrl:and"
          constraints:
            - leftOperand: "UsagePurpose"
              operator: "eq"
              rightOperand: "cx.core.digitalTwinRegistry:1"
            - leftOperand: "Membership"
              operator: "eq"
              rightOperand: "active"
        - action: "use"
          constraints:
            - leftOperand: "BusinessPartnerNumber"
              operator: "eq"
              rightOperand: "BPNL1TEST12342321"
      prohibition: []
      obligation: []
```

**Comment by matbmoser** [comment]
What is still missing:
- Comparation mechanism for checking the complete policy against the actual policy.
- Unit Tests working with the different cases.

What was done:

- [x] Implemented logic to parse policy constraints in a generic way (allowing multiple logic constraints)
- [x] Implemented logic to bind the policy coming from the edc
- [x] Implemented logic to select which constraints are valid compared with the configuration

**Comment by matbmoser** [comment]
I was not happy enough with the results because it was confusing what to apply when which policy to choose if it was valid.

So I am just including all the policy structure in the configuration and then parsing it in the constructor from the policy class.

I created a test that shows and checks for the parsing from the configuration to a actual policy structure with constraints:

```java
2024-04-17 15:36:37,698 |INFO| [testLogThread] u.LogUtil$LogPrinter: |17724|0,12| [TEST] [INPUT]: [ {
  "permission" : [ {
    "action" : "use",
    "logicalConstraint" : "odrl:and",
    "constraints" : [ {
      "leftOperand" : "cx-policy:UsagePurpose",
      "operator" : "eq",
      "rightOperand" : "cx.core.digitalTwinRegistry:1"
    }, {
      "leftOperand" : "Membership",
      "operator" : "eq",
      "rightOperand" : "active"
    } ]
  } ],
  "obligation" : [ ],
  "prohibition" : [ ]
} ]
2024-04-17 15:36:37,706 |INFO| [testLogThread] u.LogUtil$LogPrinter: |17724|0,12| [TEST] [RESPONSE]: [ {
  "odrl:permission" : [ {
    "odrl:action" : "use",
    "odrl:constraint" : {
      "odrl:and" : [ {
        "odrl:leftOperand" : "cx-policy:UsagePurpose",
        "odrl:operator" : {
          "@id" : "eq"
        },
        "odrl:rightOperand" : "cx.core.digitalTwinRegistry:1"
      }, {
        "odrl:leftOperand" : "Membership",
        "odrl:operator" : {
          "@id" : "eq"
        },
        "odrl:rightOperand" : "active"
      } ]
    }
  } ],
  "odrl:prohibition" : [ ],
  "odrl:obligation" : [ ]
} ]

````

**Comment by matbmoser** [comment]
Then the format from the configuration will look something like this:

```yaml


    policyCheck:
      enabled: true
      # List of allowed permissions policies
      policies:
        - permission:
          - action: "use"
            logicalConstraint: "odrl:and"
            constraints:
            - leftOperand: "cx-policy:UsagePurpose"
              operator: "eq"
              rightOperand: "cx.core.digitalTwinRegistry:1"
            - leftOperand: "Membership"
              operator: "eq"
              rightOperand: "active"
          prohibition: []
          obligation: []


```
If there is more policies you just do like this:

    policyCheck:
      enabled: true
      # List of allowed permissions policies
      policies:
        - permission:
          - action: "use"
            logicalConstraint: "odrl:and"
            constraints:
            - leftOperand: "cx-policy:UsagePurpose"
              operator: "odrl:eq"
              rightOperand: "cx.core.digitalTwinRegistry:1"
            - leftOperand: "Membership"
              operator: "odrl:eq"
              rightOperand: "active"
          prohibition: []
          obligation: []
        - permission:
          - action: "use"
            constraints:
            - leftOperand: "cx-policy:BusinessPartnerNumber"
              operator: "odrl:eq"
              rightOperand: "BPNL121320AS21320"
          prohibition: []
          obligation: []
        - permission:
          - action: "use"
            logicalConstraint: "odrl:or"
            constraints:
            - leftOperand: "cx-policy:UsagePurpose"
              operator: "odrl:eq"
              rightOperand: "cx.core.digitalTwinRegistry:2"
            - leftOperand: "Membership"
              operator: "odrl:eq"
              rightOperand: "active"
          prohibition: []
          obligation: []
